# Generated by Django 4.2.6 on 2024-01-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0008_alter_achievement_end_date_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
