# Generated by Django 4.2.6 on 2024-01-09 19:46

import achievements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='qrcode',
            field=models.ImageField(default=1, upload_to=achievements.models.upload_function_qr),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(null=True, upload_to=achievements.models.upload_function),
        ),
    ]
