# Generated by Django 4.2.6 on 2024-01-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('achievements', '0003_alter_achievement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
