# Generated by Django 4.2.6 on 2024-01-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_rename_langitude_achievement_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='achievement',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
