# Generated by Django 4.2.6 on 2024-01-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0006_achievement_description_achievement_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
