# Generated by Django 4.2.6 on 2024-01-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0007_achievement_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
